### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by robwilkerson** [nlf/node-github-hook#33]
I have a dev box running the listener on `:1221` for one project and it's working great. I'm trying to add a new listener on `:1222` for a second project. The listener seems to be running fine:

```
$ sudo netstat -ltnp | grep node
tcp        0      0 0.0.0.0:1221            0.0.0.0:*               LISTEN      9790/node
tcp        0      0 0.0.0.0:1222            0.0.0.0:*               LISTEN      10711/node
```

Looks good as far as I can tell, but when I push, the following error is logged:

```
POST /mandrel-web 192.30.252.46
received 8244 bytes from 192.30.252.46
got push event on mandrel-web:refs/heads/master from 192.30.252.46
internal/child_process.js:302
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:893:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:367:9)
    at Object.exports.execFile (child_process.js:139:15)
    at null.<anonymous> (/usr/lib/node_modules/githubhook/bin/githubhook:52:17)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at /usr/lib/node_modules/githubhook/index.js:140:22
    at GithubHook.getSecret (/usr/lib/node_modules/githubhook/index.js:254:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/githubhook/index.js:78:14)
```

**Comment by robwilkerson** [comment]
Apologies. Looks like this was something on my end. It started working and has been okay ever since.
